apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
      - name: tech-challenge-app
        image: 407549602436.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-app-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: tech-challenge-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-app
  ports:
  - port: 80
    targetPort: 3000
