apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app
  labels:
    app: tech-challenge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
        - name: tech-challenge-app
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-app-k8s:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            # - name: CUSTOMERS_TABLE
            #   value: "Customers"
            # - name: PRODUCTS_TABLE
            #   value: "Products"
            # - name: ORDERS_TABLE
            #   value: "Orders"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: tech-challenge-app
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
